health:
    path: /healthcheck
    methods: GET
    controller: SymfonyHealthCheckBundle\Controller\HealthController::check

#ping:
#    path: /ping
#    methods: GET
#    controller: SymfonyHealthCheckBundle\Controller\PingController::check
