controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

ekreative_health_check:
    resource: '@EkreativeHealthCheckBundle/Resources/config/routes.xml'
